function EnableLog(loggerName: string, open: boolean): void;
function LogEvent(loggerName: string, message: string): void;
function XQuery(sql: string): object;
function ArrayDirect(array: any): object;
function ArrayCount(array: any): number;
function ArrayOptFirstElem(value: object): object; // undefined
function ArrayOptFirstElem(value: object, returnValue: object): object;
function ArraySort(array: any, field: string, orderBy: string): any;
function DateToRawSeconds(date: any): number;
function StrReal(number: number, digits: number): string;
function OpenNewDoc(path: string): object;
function EncodeJson(object: any): string;
function Int(value: any): number;
function OptInt(value: any): number;
function OptInt(value: any, value1: any ): number;
function Sleep(delay: any): void;
function ParseDate(date: any): string;
function DropFormsCache(cacheMask: string): void;
function StrCharCount(value: string): number;
function Trim(value: string): string;
function OptReal(value: any): number;
function Date(): any;
function Date(value: string): any;
function DateOffset(date: any, seconds: number);
function StrDate(date: any): any;
function StrDate(date: any, showTime: boolean): any;
function StrDate(date: any, showTime: boolean, showSeconds: boolean): any;
function OptDate(date: any) : string;
function UrlFromDocID(value: number): string;
function UrlFromDocID(value: number, dbName: string): string;
function DeleteDoc(url: string): void;
function ArrayOptFindByKey(list: object, key: any, field: string);
function ArrayOptFind(array: any, expression: string);
function StrUpperCase(value: string): string;
function StrLowerCase(value: string): string;
function StrCharRangePos(value: string, start: number, stop: number): string;
function StrBegins(value: string, part: string): boolean;
function StrBegins(value: string, part: string, ignoreCase: boolean): boolean;
function ArrayFirstElem(value: any): object;
function CallServerMethod(library: string, method: string, value: any): object;
function CopyUrl(path: string, value: object): void;
function StrReplace(value: string, pattern: string, replacement: string): string;
function StrToCharArray(value: string): any;
function ArrayExtractKeys(array: any, tagName: string): any;
function StrContains(targetString: string, searchString: string): boolean;
function StrContains(targetString: string, searchString: string, ignoreCase: boolean): boolean;
function StrRangePos(targetString: string, start: number, finish: number): string;
function Day(datetime: any): number;
function Month(datetime: any): number;
function Year(datetime: any): number;
function Hour(datetime: any): number;
function Minute(datetime: any): number;
function Second(datetime: any): number;
function WeekDay(datetime: any): number;
function DeleteFile(url: string): void;
function OpenDoc(url: string): object;
function UrlToFilePath(s: string): any;
function ObtainSessionTempFile(s: string): any;
function UrlPathSuffix(s: string): any;
function ArraySelectAll(o: object): any;
function ArraySelectDistinct(o: object, column: string) : any;
function ArrayMerge(a: any, column: string, s: string): any;
function ArrayExtract(array: any, field: string): any;
function StrLeftCharRange(datetime: any, length: number) : string